name: Deploy
on:
  push:
    branches: ["feat/dev"]
  workflow_dispatch:
jobs:
  build-project:
    name: Build and Test ParkingPatrolWebApp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: install node v18
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - name: Install Npm dependencies
        run: npm install
      #- name: Test application
      #  run: npm run test
      - name: Build application
        run: npm run build
      - name: Create .env file
        run: |
            cp .env.template .env
            echo "DATABASE_URL=${{ secrets.DEV_DATABASE_URL }}" >> .env
            echo "AUTH0_BASE_URL=${{ secrets.AUTH0_BASE_URL }}" >> .env
            echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> .env
            echo "AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}" >> .env
            echo "AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}" >> .env
            echo "AUTH0_SECRET=${{ secrets.AUTH0_SECRET }}" >> .env
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: pm4parkingpatrol/parking_patrol:dev
      - name: redeploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBERNETES_CONFIG }}
          version: v1.21.0 # specify kubectl binary version explicitly
          binaries-url: "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl" # specify the download url explicitly
          command: -n nightparkingpatrol-dev rollout restart deployment/npp-dev-deployment
