name: Build and Test ParkingPatrolWebApp
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-project:
    name: Build and Test ParkingPatrolWebApp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: install node v18
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - name: Install Npm dependencies
        run: npm install
      #- name: Test application
      #  run: npm run test
      - name: Build application
        run: npm run build
      - name: Create .env file
        run: |
          cp .env.template .env
          echo "VAR1=DiniMueter" >> .env
          echo "VAR2=DiniVater" >> .env
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: pm4parkingpatrol/test:latest, pm4parkingpatrol/test:${{ github.run_number }}
      - name: redeploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBERNETES_CONFIG }}
          version: v1.21.0 # specify kubectl binary version explicitly
          binaries-url: "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl" # specify the download url explicitly
          command: -n nightparkingpatrol-prod rollout restart deployment/test-next-deployment
